# site settings
title: j5K
subtitle: Johnny 5000
email: jrobinsonmedia@gmail.com
description: I am a funky-ass dj.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: j5k
street_address:
city: Saratoga Springs
state: NY
zip_code: 12866
country: United States of America
#phone:

# homepage tiles
# JR: removed dependency on these
# tiles-source: pages # accepts "posts" or "pages"
# tiles-count: 12

# social settings
500px_url:
youtube_url: https://www.youtube.com/channel/UCng8vRKQJWhLqGkJsldKrmA
facebook_url: https://www.facebook.com/j5kmusic
instagram_url: https://instagram.com/djj5k
twitter_url: https://twitter.com/djj5k

# build settings
markdown: kramdown

sass:
  style: compressed

excerpt_separator: <!--more-->
show_featured: false
